language: objective-c

xcode_project: TCXZpot.xcodeproj
xcode_scheme: TCXZpot-Swift
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3

script:
- xcodebuild -list -project TCXZpot.xcodeproj
- xcodebuild clean build test -project TCXZpot.xcodeproj -scheme TCXZpot-Swift -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3'
